# CNN Model Configuration
base_config: "base_config.yaml"

model:
  name: "AdvancedCNN"
  type: "convolutional"
  window_length: 25
  feature_num: 13
  
  architecture:
    conv_layers:
      - filters: 64
        kernel_size: 3
        activation: "relu"
        padding: "same"
      - filters: 32
        kernel_size: 3
        activation: "relu"
        padding: "same"
      - filters: 16
        kernel_size: 2
        activation: "relu"
        padding: "same"
    
    dense_layers:
      - units: 100
        activation: "relu"
        dropout: 0.3
      - units: 50
        activation: "relu"
        dropout: 0.2
      - units: 1
        activation: "linear"
    
    batch_norm: true
    l2_regularization: 0.001

  compilation:
    optimizer: "adam"
    loss: "mse"
    metrics: ["mae", "mse"]

training:
  batch_size: 32
  epochs: 200
  early_stopping:
    monitor: "val_loss"
    patience: 20
    restore_best_weights: true
  reduce_lr:
    monitor: "val_loss"
    factor: 0.5
    patience: 10
    min_lr: 0.00001

data:
  sequence:
    window_length: 25
    stride: 1
    sampling_rate: 1
  scaling: "minmax"
  train_engines: 100
  test_engines: 50

experiment:
  tracking: true
  mlflow_tracking_uri: "logs/mlruns"
  experiment_name: "cnn_rul_prediction"
  save_best_model: true